- hosts: web
  gather_facts: false
  become: yes

  tasks:
    - name: Install Docker
      raw: yum install -y docker

    - name: Start Docker
      raw: systemctl start docker && systemctl enable docker

    - name: Pull Docker Image
      raw: docker pull kenneth4/motion-fe:0.1

    - name: Stop old container if exists
      raw: docker rm -f motion-fe || true

    - name: Run Container
      raw: docker run -d -p 80:3000 --name motion-fe kenneth4/motion-fe:0.1
