- hosts: web
  gather_facts: false
  become: yes

  tasks:
    - name: Install Docker
      raw: yum install -y docker

    - name: Start Docker service
      raw: systemctl start docker && systemctl enable docker

    - name: Add ec2-user to docker group
      raw: usermod -aG docker ec2-user

    - name: Pull Docker image
      raw: docker pull kenneth4/motion-fe:latest

    - name: Stop old container if it exists
      raw: docker rm -f motion-fe || true

    - name: Run container
      raw: docker run -d -p 80:3000 --name motion-fe kenneth4/motion-fe:latest
